---
abstract: 'Sitemap support for Catalyst.'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Catalyst: '0'
  Catalyst::Controller: '0'
  Catalyst::Test: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  lib: '0'
  parent: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.040, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-Sitemap
provides:
  Catalyst::Plugin::Sitemap:
    file: lib/Catalyst/Plugin/Sitemap.pm
    version: v1.0.2
requires:
  List::Util: '0'
  Moose::Role: '0'
  WWW::Sitemap::XML: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Catalyst-Plugin-Sitemap/issues
  homepage: https://github.com/yanick/Catalyst-Plugin-Sitemap
  repository: https://github.com/yanick/Catalyst-Plugin-Sitemap.git
version: 1.0.2
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Alex J. G. Burzyński <ajgb@cpan.org>'
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
